spring:
  application:
    name: azura-api
    api-key: ${API_KEY}
    gateway-key: ${GATEWAY_KEY}
    gateway-url: "http://localhost:8090" # Be careful, check if the port is correct for localhost, or the uri if the fake gateway is up
  datasource:
    url: jdbc:postgresql://localhost:5432/azura
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Use 'update' for development, 'validate' for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  key: "${JWT_KEY}"
  expiration: ${JWT_EXPIRATION:900000} # 15 min